name: CI

on:
  push:
    tags: [ "v*" ]

  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "下载文件"
        run: |
          mkdir -p ${{ github.workspace }}/download

          while read line; do
              url=$(awk '{$1=$1}1' <<<"${line%%-->*}")
              file=$(awk '{$1=$1}1' <<<"${line##*-->}")
              echo "==> curl -sL $url -o ${{ github.workspace }}/download/$file"
              curl -sL $url -o ${{ github.workspace }}/download/$file
          done < <(egrep -v "^$|^#" list.txt)

      - uses: actions/upload-artifact@v4
        with:
          name: download
          path: ${{ github.workspace }}/download

  create_release:
    needs:
      - download

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: download
          path: ./download

      - name: Get tag message
        run: |
          echo -e "> Automated release created by GitHub Actions.\n" > ${{ github.workspace }}/RELEASE.md
          GITHUB_REF=${{ github.ref }}
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          git tag -l --format='%(contents)' "${TAG_NAME}" | tee -a ${{ github.workspace }}/RELEASE.md

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/download/*"
          bodyFile: ${{ github.workspace }}/RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
